name: smart_campus
description: A Smart Campus application for managing attendance and courses.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Dependency Injection
  get_it: ^7.6.0
  injectable: ^2.1.2
  # Database
  sqflite: ^2.3.0
  # Network
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  # Storage
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  # Security
  encrypt: ^5.0.1
  # JSON Serialization
  json_annotation: ^4.8.1
  # Utils
  logger: ^2.0.2
  uuid: ^3.0.7
  intl: ^0.18.1
  # Device Info
  device_info_plus: ^9.0.3
  # Location
  geolocator: ^10.0.1
  # WiFi
  wifi_scan: ^0.4.0+2
  network_info_plus: ^4.1.0
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  lottie: ^2.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  # State Management
  provider: ^6.1.1
  rxdart: ^0.27.7
  path: ^1.8.3
  # Permission handling
  permission_handler: ^11.0.1
  # Error tracking and monitoring
  sentry_flutter: ^7.16.1
  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  # For phone authentication UI
  pinput: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
